CREATE TABLE billers (
    id UUID PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(30) NOT NULL, -- TELECOM, ELECTRICITY, INTERNET, WATER
    supported_currency VARCHAR(3) NOT NULL DEFAULT 'YER',
    wallet_id UUID NOT NULL REFERENCES wallets (id),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);